### ISSUE TITLE
vagrant building different OS to base OS

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#65]
if we are on ubuntu, but building a centos build, the OS detects /etc/issue on local machine, needs to use booting vm instead

 OS=`head -n1 /etc/issue | cut -f1 -d\ `
+OS="CentOS"

**Comment by marsbard** [comment]
pretty sure I just fixed this when merging the develop branch

**Comment by digcat** [comment]
still seeing this as an issue when trying to build centos on a ubuntu, /etc/issue returns ubuntu, should be running on the vm, not local os

**Comment by marsbard** [comment]
Have you got a line like this in your Vagrantfile?  Note that it runs install/modules-for-vagrant.sh from the vagrant context now (i.e. it changes dir to `/vagrant`
```
26   config.vm.provision :shell do |shell|
 27     shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; then apt-get update; else yum -y update; fi; cd /vagrant; install/modules-for-vagrant.sh"
 28   end
```

**Comment by digcat** [comment]
Yes, have this in the Vagrant file already


config.vm.provision :shell do |shell|
     shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; if 
[ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; then apt-get update; 
else yum -y update; fi; cd /vagrant; install/modules-for-vagrant.sh"
   end

**Comment by marsbard** [comment]
So when you do `vagrant up` or `vagrant provision` it should install the modules into `/vagrant/modules` including epel if you are in a centos context

tbh I really don't care about centos for this release. If you can't close this then move it to milestone 1.1. thanks

**Comment by digcat** [comment]
yep no problem, work around is to hard code the OS flag to Centos which seems to do the trick.

**Comment by marsbard** [comment]
"So when you do vagrant up or vagrant provision it should install the modules into /vagrant/modules including epel if you are in a centos context" - this must be happening when you run vagrant provisioning, so I don't get why the ticket is open

**Comment by digcat** [comment]
yes this is fixed now.
